### 课程查询接口
POST http://{{content_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
  "audioStatus":"202004",
  "courseName":"",
  "publishStatus":""
}

### 课程分类查询接口
GET  http://{{content_host}}/content/course-category/tree-nodes