### 课程查询接口
POST http://{{content_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
  "audioStatus":"202004",
  "courseName":"",
  "publishStatus":""
}

### 课程分类查询接口
GET  http://{{content_host}}/content/course-category/tree-nodes


### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
"charge": "201001",
"price": 0,
"originalPrice":0,
"qq": "22333",
"wechat": "223344",
"phone": "13333333",
"validDays": 365,
"mt": "1-1",
"st": "1-1-1",
"name": "hhhh",
"pic": "",
"teachmode": "200002",
"users": "初",
"tags": "",
"grade": "204001",
"description": "",
"objectives": ""
}

### 测试查看课程计划
GET {{gateway_host}}/content/teachplan/74/tree-nodes
Content-Type: application/json

### 测试上传文件
POST {{media_host}}/media/upload/coursefile
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="1.png"
Content-Type: application/octet-stream

< D:/DeskTop/1.png

### 测试课程教师查询
GET {{gateway_host}}/content/courseTeacher/list/72


### 新增课程教师
POST {{gateway_host}}/content/courseTeacher
Content-Type: application/json

{
"courseId": 135,
"teacherName": "牛",
"position": "教师职位",
"introduction": "教师简介"
}

### 测试修改课程教师
POST {{gateway_host}}/content/courseTeacher
Content-Type: application/json

{
  "id": 21,
  "courseId": 135,
  "teacherName": "马报国",
  "position": "123",
  "introduction": "54334",
  "photograph": null,
  "createDate": null
}

### 测试认证服务 （没有令牌 拒绝访问）
GET http://{{content_host}}/content/course/2

### 使用密码模式 申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=zhy&password=111111
### 获得令牌 eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2Nzc3NDY0MzAsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjY5YWVlMDY1LTZiNzgtNGJhMy1iNGU2LTI5ZWM3ODFjNTQ2MiIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.PMBXysXQJUZERIqTKftB1u0616qQEXkE6tXgoKF5lFg
GET http://localhost:63040/content/course/135
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJiaXJ0aGRheVwiOlwiMjAyMy0wMy0wMlQxNTozNDoxNFwiLFwiY2VsbHBob25lXCI6XCIxMjNcIixcImNvbXBhbnlJZFwiOlwiMjJcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjMtMDMtMDJUMTU6MzM6NDlcIixcImVtYWlsXCI6XCJOdWxsXCIsXCJpZFwiOlwiNTNcIixcIm5hbWVcIjpcInJvb3RcIixcIm5pY2tuYW1lXCI6XCJOdWxsXCIsXCJxcVwiOlwiTnVsbFwiLFwic2FsdFwiOlwiTnVsbFwiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIjFcIixcInVwZGF0ZVRpbWVcIjpcIjIwMjMtMDMtMDJUMTU6MzQ6MjJcIixcInVzZXJuYW1lXCI6XCJ6aHlcIixcInVzZXJwaWNcIjpcIk51bGxcIixcInV0eXBlXCI6XCIxMDEwMDNcIixcInd4VW5pb25pZFwiOlwiTnVsbFwifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2Nzc3NTQ3MTEsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjBkNDk0MDJhLTA1ZGQtNDhhOS1iNzg1LTJmMzg3MTE1OGYyMyIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.njo8ruIbJpY-MPfeCeomu3D1QH4yJx1q9a0_pQiHtPs
