GET http://{{gateway_host}}/content/course/135
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2Nzc3NDY0MzAsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjY5YWVlMDY1LTZiNzgtNGJhMy1iNGU2LTI5ZWM3ODFjNTQ2MiIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.PMBXysXQJUZERIqTKftB1u0616qQEXkE6tXgoKF5lFg
